name: Conductor Code Review

on:
  pull_request:
    types: [opened, reopened, ready_for_review]
  issue_comment:
    types: [created]

jobs:
  code-review:
    # Don't run on draft PRs
    # Only run on issue comments that include '@conductor review'
    if: github.event.pull_request.draft == false || ${{ github.event_name != 'issue_comment' || contains(github.event.comment.body, '@conductor review') }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Get complete history for better context
      
      # Run Conductor code review
      - name: Conductor Code Review
        uses: conductorcodes/conductor-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
