name: Conductor Code Review

on:
  pull_request:
    types: [opened, reopened, ready_for_review]
  issue_comment:
    types: [created]

jobs:
  code-review:
    if: ${{ github.event_name != 'issue_comment' || contains(github.event.comment.body, '@conductor-codes review') }}
    runs-on: ubuntu-latest
    
    steps: 
      - name: Determine PR ref
        if: github.event_name == 'issue_comment'
        id: pr
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            core.setOutput('head_ref', pr.data.head.ref);
            
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Get complete history for better context
      
      - name: Conductor Code Review
        uses: conductor-codes/conductor-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          conductor_llm_config: ${{ secrets.CONDUCTOR_LLM_CONFIG }}
          conductor_api_key: ${{ secrets.CONDUCTOR_API_KEY }}
