name: Conductor Analysis

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  conductor:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Build and run Conductor
        uses: docker://stephenconductor/conductor:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: "gpt-4o"
          SERVER_COMMAND: "yarn dev"
          SERVER_URL: "http://localhost:3000"
          SERVER_TIMEOUT: "60000"
          INSTALL_DEPENDENCIES: "true"
          PR_NUMBER: ${{ github.event.pull_request.number }}
